[build]
  command = "npm run build && npm run export"
  publish = "/build"
  base = "/"
  command = "CI= npm run build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
  package = "@netlify/plugin-nextjs"